version: "3.8"
services:
  service1:
    image: "usermgmt:latest"
    ports:
      - 3000:3000
    deploy:
      replicas: 3
  service2:
    image: "usermgmt:latest"
    ports:
      - 3001:3000
    deploy:
      replicas: 2
